# NumPy (Numerical Python) - Übung


### Übung 1: 
Erstelle eine Übersicht in der die Gemeinsamkeiten und Unterschiede zwischen Python Listen und NumPy-Array gegenübergestellt werden 

Hinweis: diese Übersicht wird später mit Pandas ergänzt

Hilfestellung: Datentypen, Wie komme ich an ein Element?, Wie ersetze ich ein Element? etc.

### Übung 2:

Übe den Umgang mit NumPy Arrays und werde dadurch sicherer.
 

In [51]:
#Platz für deinen Code

import numpy as np

In [52]:
name = ['Hannah', 'Charlotte', 'Henning', 'Henry', 'Ida']
skills = ['Python', 'Java', 'Python', 'C', 'Python']
experience_level = [1, 2, 2, 3, 3]

In [53]:
# a. Erstelle ein Array (eindimensional) als Konstrukt, welches du im nächsten Schritt mit den Daten befüllst
new_array = np.zeros(5, dtype={'names':('name', 'skills', 'level'),
                          'formats':('U10', 'U10', 'i4')})
print(type(new_array))
print(new_array.ndim)

<class 'numpy.ndarray'>
1


In [54]:
# b. Befülle das Array Konstrukt mit den obigen Daten
new_array['name'] = name
new_array['skills'] = skills
new_array['level'] = experience_level
print(new_array)

[('Hannah', 'Python', 1) ('Charlotte', 'Java', 2) ('Henning', 'Python', 2)
 ('Henry', 'C', 3) ('Ida', 'Python', 3)]


In [71]:
# c. Wer steckt hinter dem 2.ten Element?
new_array[1]['name']

np.str_('Charlotte')

In [56]:
# d. Wer kann Python?
new_array[new_array['skills']== 'Python']['name']

array(['Hannah', 'Henning', 'Ida'], dtype='<U10')

In [57]:
# e. Wer kann Python und ist kein Anfänger?
new_array[(new_array['skills'] == 'Python') & (new_array['level'] >1)]['name']

array(['Henning', 'Ida'], dtype='<U10')

### Übung 3

Beispiele für 3D-Arrays 

In [58]:
# Beispiel 1

np_example1  = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [59]:
# Lasse dir die Dimensionen anzeigen
np_example1.ndim

3

In [60]:
# Lasse dir den Shape anzeigen - was sagt der Shape aus?
np_example1.shape

(2, 2, 2)

In [61]:
# Beispiel 2
np_example2 = np.array([[[1,2,3], [4,5,6]]])


In [62]:
# Greife auf die 3 zu
np_example2[0,0,2]

np.int64(3)

In [63]:
# Greife auf die 5 zu
np_example2[0,1,1]

np.int64(5)

In [73]:
# Beispiel 3

np_example3 = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]],[[13,14,15], [16,17,18]]])
np_example3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [79]:
# shape
np_example3.shape
np_example3[1,[0,1],[0,2]]

array([ 7, 12])

In [66]:
# Greife auf die 14 zu
np_example3[2,0,1]

np.int64(14)

In [67]:
# Greife auf die 9 zu
np_example3[1,0,2]


np.int64(9)

In [72]:
# Greife auf die 9 und 12 zu (eine Abfrage!)
#np_example3[[1, 1], [0, 1], [2, 2]]
np_example3[1,:,2]


array([ 9, 12])

In [83]:
#np_example3
np_example3[0::2,:,2]

array([[ 3,  6],
       [15, 18]])

In [85]:
# Greife auf die 3, 6, 15,18 zu
#np_example3 = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]],[[13,14,15], [16,17,18]]])

#[0,0,2], [0,1,2], [2,0,2], [2,1,2]
#np_example3[[0, 0, 2, 2], [0, 1, 0, 1], [2, 2, 2, 2]]

np_example3[[0, 2], :, 2]

array([[ 3,  6],
       [15, 18]])