In [1]:
import re

In [4]:
text = "Machine Learning benötigt   saubere Daten!"

Normalising

In [6]:
# Kleinschreibung
text = text.lower()
# Sonderzeichen ersetzen
text_clean = re.sub(r'[^a-zäöüß ]', '', text)
print(text_clean)
text_normalized = re.sub(r'\s+', ' ', text_clean).strip()
print(f"Normalisierter Text: '{text_normalized}'")

machine learning benötigt   saubere daten
Normalisierter Text: 'machine learning benötigt saubere daten'


In [ ]:
class CharArray:

    CHAR_MAP = {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5,
        '6': 6, '7': 7, '8': 8, '9': 9, ' ': 10,
        'a': 11, 'b': 12, 'c': 13, 'd': 14, 'e': 15,
        'f': 16, 'g': 17, 'h': 18, 'i': 19, 'j': 20,
        'k': 21, 'l': 22, 'm': 23, 'n': 24, 'o': 25,
        'p': 26, 'q': 27, 'r': 28, 's': 29, 't': 30,
        'u': 31, 'v': 32, 'w': 33, 'x': 34, 'y': 35,
        'z': 36, 'ä': 37, 'ö': 38, 'ü': 39, 'ß': 40
    }
    EXCLUDE = re.compile('[^0-9 a-zäüöß]+')
    BLANKS = re.compile(' +')

    def normalize(self, text):
        # Kleinschreibung
        text = text.lower()
        # Sonderzeichen ersetzen
        #print('1.',text)
        text = self.EXCLUDE.sub(' ', text)
        #print('2.1', text)
        text = text.strip(' ')
        #print('2.',text)
        # Mehrere Leerzeichen durch eins ersetzen
        text = self.BLANKS.sub(' ', text)
        #print('3.',text)
        return text

    def process(self, text):
        text = self.normalize(text)
        result = [self.CHAR_MAP[char] for char in text]
        return result

    def stats(self, text):
        chars = self.process(text)
        result = [0 for _ in range(0, 41)]
        #print('4.', result)
        for code in chars:
            result[code] += 1
#            print(result)
        return result


if __name__ == '__main__':
    ca = CharArray()
    text = '''Machine Learning benötigt saubere Daten!'''
    x = ca.normalize(text)
    print(f"Normalisierter Text: '{x}'")
    y = ca.process(text)
    print(f"Numerische Codes: \n{y}")
    print('Vergleich:', len(x), len(y))
    z  = ca.stats(text)
    print(f"Statistische Häufigkeit: {z}")
    print(sum(z))



Normalisierter Text: 'machine learning benötigt saubere daten'
Numerische Codes: 
[23, 11, 13, 18, 19, 24, 15, 10, 22, 15, 11, 28, 24, 19, 24, 17, 10, 12, 15, 24, 38, 30, 19, 17, 30, 10, 29, 11, 31, 12, 15, 28, 15, 10, 14, 11, 30, 15, 24]
Vergleich: 39 39
Statistische Häufigkeit[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 2, 1, 1, 6, 0, 2, 1, 3, 0, 0, 1, 1, 5, 0, 0, 0, 2, 1, 3, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
39


# Aufgabe 2: Bag of Words mit CountVectorizer

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
strings = [
"Machine Learning mit Python",
"Python wird für Data Science genutzt",
"Learning Algorithmen benötigen Daten"
]

string_data = np.array(strings)
print(string_data)
vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(string_data)
print(bag_of_words)
bag_of_words

['Machine Learning mit Python' 'Python wird für Data Science genutzt'
 'Learning Algorithmen benötigen Daten']
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (3, 12)>
  Coords	Values
  (0, 7)	1
  (0, 6)	1
  (0, 8)	1
  (0, 9)	1
  (1, 9)	1
  (1, 11)	1
  (1, 4)	1
  (1, 2)	1
  (1, 10)	1
  (1, 5)	1
  (2, 6)	1
  (2, 0)	1
  (2, 1)	1
  (2, 3)	1


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (3, 12)>

In [15]:
# Matrix in array umwandeln (Bag of Words Format)
bag_of_words.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]])

In [16]:
# Liste der unterschiedlichen Wörter
vectorizer.get_feature_names_out()

array(['algorithmen', 'benötigen', 'data', 'daten', 'für', 'genutzt',
       'learning', 'machine', 'mit', 'python', 'science', 'wird'],
      dtype=object)

Entfernen Sie Stoppwörter: ["mit", "für", "wird"]

In [17]:
# Stopwords für deutschen Text
stop = ["mit", "für", "wird"]
vectorizer2 = CountVectorizer(stop_words = stop)
bag_of_words = vectorizer2.fit_transform(string_data)
bag_of_words.toarray()

array([[0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 0, 0]])

Geben Sie die Feature-Namen 

In [18]:
# Liste der unterschiedlichen Wörter
vectorizer2.get_feature_names_out()

array(['algorithmen', 'benötigen', 'data', 'daten', 'genutzt', 'learning',
       'machine', 'python', 'science'], dtype=object)

# Aufgabe 3: Bigramme erzeugen

In [19]:
vectorizer3 = CountVectorizer(stop_words = stop, ngram_range = (2, 2))
bigrams = vectorizer3.fit_transform(string_data)
vectorizer3.get_feature_names_out()

array(['algorithmen benötigen', 'benötigen daten', 'data science',
       'learning algorithmen', 'learning python', 'machine learning',
       'python data', 'science genutzt'], dtype=object)

# Aufgabe 4: Große Texte mit HashingVectorizer komprimieren

In [25]:
texts = [
"""Ein tagged VLAN (Virtual Local Area Network) nach dem Standard IEEE 802.1Q ist eine Methode,
 um mehrere getrennte Netzwerke über ein und dasselbe physische Kabel zu schicken.
Stellen Sie sich ein VLAN wie eine Trennwand in einem Büro vor. Ein tagged VLAN ist dann wie ein Postsystem, 
bei dem jeder Brief einen Aufkleber (Tag) erhält, damit der Empfänger weiß, in welche Abteilung (VLAN) der Brief gehört.
1. Das Problem ohne Tagging
Normalerweise gehört ein Port an einem Switch zu genau einem Netzwerk. 
Wenn Sie 3 verschiedene Netzwerke (z. B. Buchhaltung, Gäste-WLAN und Produktion) von einem Switch zum nächsten übertragen wollten, 
müssten Sie 3 separate Kabel ziehen.

2. Die Lösung: Der "Tag"
Beim Tagging wird in den Header jedes Datenpakets (Ethernet-Frame) eine kleine Information eingefügt: die VLAN-ID (eine Zahl zwischen 1 und 4094).
Der Prozess: Wenn ein Paket einen Switch verlässt,
 um über eine Verbindungsleitung (Trunk) zu einem anderen Switch zu gehen, klebt der Switch das "Tag" auf das Paket.

Der Empfang: Der Ziel-Switch liest das Tag, sieht z. B. "VLAN 20", entfernt das Tag wieder und leitet das Paket nur an die Anschlüsse weiter,
 die ebenfalls zum VLAN 20 gehören.
"""]

In [27]:
from sklearn.feature_extraction.text import HashingVectorizer
import numpy as np

text_data = np.array(texts)
hv = HashingVectorizer(n_features = 10)


In [29]:
features = hv.transform(text_data)
#print(features)
features.toarray()

array([[-0.17149859, -0.45732956, -0.0571662 ,  0.22866478, -0.45732956,
         0.17149859, -0.17149859,  0.11433239, -0.40016337, -0.51449576]])